name: Super-Linter
 on:
  label:
    types:
      - created
  push:
    branches:
      - main
  page_build:
env:
  AZURE_WEBAPP_NAME: your-app-name
  AZURE_WEBAPP_PACKAGE_PATH:
  NODE_VERSION: '14.x'
permissions:
  contents: 
     - read
jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
