name: Blank
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pipe-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "pipe-build - Hello, world!"
        
  pipe-security:
    runs-on: ubuntu-latest
    environment:
      name: desenvolvimento
    # Depende da execu;cão do pipe-build
    needs: pipe-build
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "pipe-security - Hello, world!"
  pipe-deployment:
    runs-on: ubuntu-latest
    # Depende da execu;cão do pipe-security    
    needs: pipe-security
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "pipe-deployment - Hello, world!"
  pipe-iac:
    runs-on: ubuntu-latest
    needs:  pipe-deployment
    # Depende da execu;cão do pipe-deployment
    steps:
      - uses: actions/checkout@v4
  pipe-doc:
    runs-on: ubuntu-lates 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get the latest tag
        id: get_tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "latest_tag=$LATEST_TAG"
